using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;

namespace EasyExcel
{
	/// <summary>
	///     Excel Converter
	/// </summary>
	public static partial class EEConverter
	{
		public static void GenerateCSharpFiles(string excelPath, string csPath)
		{
			try
			{
				excelPath = excelPath.Replace("\\", "/");
				csPath = csPath.Replace("\\", "/");

				if (!Directory.Exists(excelPath))
				{
					EditorUtility.DisplayDialog("EasyExcel", "Excel files path doesn't exist.", "OK");
					return;
				}

				if (!Directory.Exists(csPath))
				{
					var opt = EditorUtility.DisplayDialogComplex("EasyExcel",
						string.Format(
							"EasyExcelSettings CSharpPath doesn't exist. Would you like to create it?\n{0}",
							csPath),
						"Create", "Cancel", "Quit");
					switch (opt)
					{
						case 0:
							Directory.CreateDirectory(csPath);
							break;
						case 1:
						case 2:
							return;
					}
				}

				var tmpPath = Environment.CurrentDirectory + "/EasyExcelTmp/";
				if (Directory.Exists(tmpPath))
					Directory.Delete(tmpPath, true);
				Directory.CreateDirectory(tmpPath);

				excelPath = excelPath.Replace("\\", "/");
				csPath = csPath.Replace("\\", "/");
				if (!csPath.EndsWith("/"))
					csPath += "/";

				var csChanged = false;
				var filePaths = Directory.GetFiles(excelPath);
				for (var i = 0; i < filePaths.Length; ++i)
				{
					var excelFilePath = filePaths[i].Replace("\\", "/");
					if (i + 1 < filePaths.Length)
						UpdateProgressBar(i + 1, filePaths.Length, "");
					else
						ClearProgressBar();
					if (!IsExcelFile(excelFilePath))
						continue;
					var newCsDict = ToCSharpArray(excelFilePath);
					foreach (var newCs in newCsDict)
					{
						var cSharpFileName = EESettings.Current.GetCSharpFileName(newCs.Key);
						var tmpCsFilePath = tmpPath + cSharpFileName;
						var csFilePath = csPath + cSharpFileName;
						var shouldWrite = true;
						if (File.Exists(csFilePath))
						{
							var oldCs = File.ReadAllText(csFilePath);
							shouldWrite = oldCs != newCs.Value;
						}

						if (!shouldWrite)
							continue;
						csChanged = true;
						var streamwriter = new StreamWriter(tmpCsFilePath, false);
						streamwriter.Write(newCs.Value);
						streamwriter.Flush();
						streamwriter.Close();
					}
				}

				if (csChanged)
				{
					EditorPrefs.SetBool(csChangedKey, true);
					var files = Directory.GetFiles(tmpPath);
					foreach (var s in files)
					{
						var p = s.Replace("\\", "/");
						File.Copy(s, csPath + p.Substring(p.LastIndexOf("/", StringComparison.Ordinal)), true);
					}

					Directory.Delete(tmpPath, true);
					AssetDatabase.Refresh();
					EELog.Log("Scripts are generated, wait for generating assets...");
				}
				else
				{
					EELog.Log("No CSharp files changed, begin generating assets...");
					ClearProgressBar();
					var historyExcelPath = EditorPrefs.GetString(excelPathKey);
					if (!string.IsNullOrEmpty(historyExcelPath))
						GenerateScriptableObjects(historyExcelPath, Environment.CurrentDirectory + "/" + EESettings.Current.GeneratedAssetPath);
				}
			}
			catch (Exception e)
			{
				EELog.LogError(e.ToString());
				EditorPrefs.SetBool(csChangedKey, false);
				ClearProgressBar();
				AssetDatabase.Refresh();
			}
		}
		
		private static Dictionary<string, string> ToCSharpArray(string excelPath)
		{
			var lst = new Dictionary<string, string>();
			var book = EEWorkbook.Load(excelPath);
			if (book == null)
				return lst;
			foreach (var sheet in book.sheets)
			{
				if (sheet == null)
					continue;
				if (!IsValidSheet(sheet))
				{
					EELog.Log(string.Format("Skipped sheet {0} in file {1}.", sheet.name, excelPath));
					continue;
				}
				var sheetData = ToSheetData(sheet);
				var csTxt = ToCSharp(sheetData, sheet.name);
				lst.Add(sheet.name, csTxt);
			}
			return lst;
		}

		private static string ToCSharp(SheetData sheetData, string sheetName)
		{
			try
			{
				var rowDataClassName = EESettings.Current.GetRowDataClassName(sheetName);
				var dataTableClassName = EESettings.Current.GetDataTableClassName(sheetName);
				var csFile = new StringBuilder(2048);
				csFile.Append(@"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasyExcel.");
				csFile.Append("\n//     Runtime Version: " + EEConstant.Version + "\n");
				csFile.Append(@"//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------");

				csFile.Append("\nusing System;\nusing System.Collections.Generic;\nusing UnityEngine;\nusing EasyExcel;\n\n");
				csFile.Append(string.Format("namespace {0}\n", EESettings.Current.NameSpace));
				csFile.Append("{\n");
				csFile.Append("\t[Serializable]\n");
				csFile.Append("\tpublic class " + rowDataClassName + " : RowData\n");
				csFile.Append("\t{\n");

				var columnCount = 0;
				for (var col = 0; col < sheetData.columnCount; col++)
				{
					if (string.IsNullOrEmpty(sheetData.Get(EESettings.Current.NameRowIndex, col)))
						break;
					columnCount++;
				}

				// Get variable names
				var variableName = new string[columnCount];
				for (var col = 0; col < columnCount; col++)
					variableName[col] = sheetData.Get(EESettings.Current.NameRowIndex, col);

				// Get variable types
				var variableLength = new string[columnCount];
				var variableType = new string[columnCount];
				// skip column 0 for ID
				for (var col = 1; col < columnCount; col++)
				{
					var cellInfo = sheetData.Get(EESettings.Current.TypeRowIndex, col);
					variableLength[col] = null;
					variableType[col] = cellInfo;

					if (cellInfo.EndsWith("]"))
					{
						var startIndex = cellInfo.IndexOf('[');
						variableLength[col] = cellInfo.Substring(startIndex + 1, cellInfo.Length - startIndex - 2);
						variableType[col] = cellInfo.Substring(0, startIndex);
					}

					var varName = variableName[col];
					var varLen = variableLength[col];
					var varType = variableType[col];

					if (varType.Equals("int") || varType.Equals("float") ||
					    varType.Equals("double") || varType.Equals("long") ||
					    varType.Equals("string") || varType.Equals("bool") ||
					    varType.Equals("JObject"))
					{
						if (varLen == null)
							csFile.Append("\t\tpublic " + varType + " " + varName + ";\n");
						else
							csFile.Append("\t\tpublic " + varType + "[] " + varName + ";\n");
					}
				}

				//string[] variableDefaults = new string[columnCount];
				csFile.Append("\n#if UNITY_EDITOR\n");
				csFile.Append("\t\tpublic override int _init(List<List<string>> sheet, int row, int column)" + "\n");
				csFile.Append("\t\t{" + "\n");
				csFile.Append("\t\t\tcolumn = base._init(sheet, row, column);\n");
				// skip column 0 for ID
				for (var col = 1; col < columnCount; col++)
				{
					var varType = variableType[col];

					/*variableDefaults[col] = sheetData.At(EasyExcelSettings.Current.DEFAULT_VALUE_ROW_INDEX, col);
					if (varType.Equals("bool"))
					{
						if (variableDefaults[col].Equals("0"))
							variableDefaults[col] = "false";
						else
							variableDefaults[col] = "true";
					}

					string varDefault = variableDefaults[col];*/
					var varLen = variableLength[col];
					var varName = variableName[col];

					if (varType.Equals("int") || varType.Equals("float") || varType.Equals("double") ||
					    varType.Equals("long") || varType.Equals("bool"))
					{
						if (varLen == null)
						{
							//csFile += "\t\t" + varName + " = " + varDefault + ";\n";
							csFile.Append("\t\t\t" + varType + ".TryParse(sheet[row][column++], out " + varName + ");\n");
						}
						else
						{
							csFile.Append("\t\t\tstring[] " + varName + "Array = sheet[row][column++].Split(\',\');" + "\n");
							csFile.Append("\t\t\tint " + varName + "Count = " + varName + "Array.Length;" + "\n");
							csFile.Append("\t\t\t" + varName + " = new " + varType + "[" + varName + "Count];\n");
							csFile.Append("\t\t\tfor(int i = 0; i < " + varName + "Count; i++)\n");
							csFile.Append("\t\t\t\t" + varType + ".TryParse(" + varName + "Array[i], out " + varName + "[i]);\n");
						}
					}
					else if (varType.Equals("string"))
					{
						if (varLen == null)
						{
							//csFile += "\t\t\tif(sheet[row][column] == null)" + "\n";
							csFile.Append("\t\t\t" + varName + " = sheet[row][column++] ?? \"" + /*varDefault + */"\";\n");
							//csFile += "\t\t\telse" + "\n";
							//csFile += "\t\t\t\t" + varName + " = sheet[row][column];\n";
						}
						else
						{
							csFile.Append("\t\t\tstring[] " + varName + "Array = sheet[row][column++].Split(\',\');" + "\n");
							csFile.Append("\t\t\tint " + varName + "Count = " + varName + "Array.Length;" + "\n");
							csFile.Append("\t\t\t" + varName + " = new " + varType + "[" + varName + "Count];\n");
							csFile.Append("\t\t\tfor(int i = 0; i < " + varName + "Count; i++)\n");
							csFile.Append("\t\t\t\t" + varName + "[i] = " + varName + "Array[i];\n");
						}
					}
				}

				csFile.Append("\t\t\treturn column;\n");
				csFile.Append("\t\t}\n#endif\n");

				csFile.Append("\t}\n\n");

				// DataTable class
				csFile.Append("\tpublic class " + dataTableClassName + " : RowDataCollection\n");
				csFile.Append("\t{\n");
				csFile.AppendFormat("\t\t[SerializeField]\n\t\tprivate List<{0}> elements = new List<{0}>();\n\n", rowDataClassName);

				csFile.AppendFormat("\t\tpublic override void AddData(RowData data)\n\t\t{{\n\t\t\telements.Add(data as {0});\n\t\t}}\n\n", rowDataClassName);
				csFile.Append("\t\tpublic override int GetDataCount()\n\t\t{\n\t\t\treturn elements.Count;\n\t\t}\n\n");
				csFile.Append("\t\tpublic override RowData GetData(int index)\n\t\t{\n\t\t\treturn elements[index];\n\t\t}\n");

				csFile.Append("\t}\n");
				
				csFile.Append("}\n");

				return csFile.ToString();
			}
			catch (Exception ex)
			{
				EELog.LogError(ex.ToString());
			}

			return "";
		}
	}
}